ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "homeAddress" TEXT;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "homeLat" DOUBLE PRECISION;
ALTER TABLE "profiles" ADD COLUMN IF NOT EXISTS "homeLng" DOUBLE PRECISION;
